version: '2'
services:

  # Redis cluster needed for STREAM events (Single node, development only)
  redis:
    image: 'redis:7'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./_data/redis:/data
    ports:
      - '6379:6379'
